[package]
name = "mcp-sdk"
version = "0.0.1"
edition = "2021"
description = "Rust Implementation of Model Context Protocol (MCP)"
repository = "https://github.com/AntigmaLabs"

license = "Apache-2.0"
[dependencies]
